config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    resources :courses, except: :destroy
    resources :subjects
  end

  resources :users, except: :destroy
  resources :courses
  resources :course_management_users, only: :create
  resources :tasks
  resources :subjects
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :tasks

  belongs_to :user, foreign_key: :creator_id

  has_many :user_subjects
  has_many :users, through: :user_subjects

  has_many :course_subjects
  has_many :courses, through: :course_subjects

  validates :name, presence: true,
    length: {maximum: Settings.name_length_maximum,
             minimum: Settings.name_length_minimum}
  validates :description, presence: true,
    length: {maximum: Settings.content_text_max_length}
  mount_uploader :thumbnail, ThumbnaiUploader

  scope :sort_subject, ->{order id: :desc}

  delegate :full_name, to: :user
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < ApplicationController
  before_action :load_subject, except: [:index, :create, :new]

  def index
    @subjects = Subject.sort_subject
                       .paginate per_page: Settings.parger, page: params[:page]
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash[:success] = t "controller.admin.subjects.save_success"
      redirect_to admin_subjects_path
    else
      flash[:danger] = t "controller.admin.subjects.save_error"
      render :new
    end
  end

  def edit; end

  def update
    if @subject.update_attributes subject_params
      flash[:success] = t "controller.admin.subjects.update_success"
      redirect_to admin_subjects_path
    else
      flash[:danger] = t "controller.admin.subjects.update_error"
      render :edit
    end
  end

  private

  def subject_params
    params.require(:subject).permit :id, :name, :description, :thumbnail,
      :time_start, :time_end, :status
  end

  def load_subject
    @subject = Subject.find_by id: params[:id]
    return if @subject
    flash[:warning] = t "controller.admin.subjects.not_find"
    redirect_to admin_subjects_path
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :logged_in_user
  before_action :load_subject, only: :show

  def show; end

  private

  def load_subject
    @subject = Subject.find_by id: params[:id]
    return if @subject
    flash[:danger] = t "controller.subjects.subject_notfound"
    redirect_to courses_path
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/admin/subjects/_form.html.erb
<%= form_for [:admin, @subject]  do |f| %>
  <%= render "layouts/shared/error_message", object: f.object %>

  <%= f.label t ".name" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label t ".description" %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.label t ".thumbnail" %>
  <%= f.file_field :thumbnail, accept: Settings.picture, class: "form-control" %>

  <%= f.label t ".time_start" %>
  <%= f.text_field :time_start, class: "form-control" %>

  <%= f.label t ".time_end" %>
  <%= f.text_field :time_end, class: "form-control" %>

  <%= f.label t ".status" %>
  <%= f.text_field :status, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/subjects/_subject.html.erb
<tr>
    <th><%= link_to subject.name, "#" %> </th>
    <th><%= subject.description %> </th>
    <th class="col-xs-6 col-md-3"><%= image_tag subject.thumbnail.url, class:"thumbnail" if subject.thumbnail? %></th>
    <th><%= l(subject.time_start, format: :default) %></th>
    <th><%= l(subject.time_end, format: :default) %></th>
    <th><%= subject.status %> </th>
    <th><%= link_to t(".edit"), edit_admin_subject_path(subject) %> </th>
    <th><%= link_to t(".delete"), admin_subject_path(subject), method: :delete,
      data: { confirm: t(".sure") } %> </th>
</tr>

app/views/admin/subjects/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".update") %>
<h1><%= t ".update" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/subjects/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".list" %></h1>
<div>
  <%= link_to t(".create"), new_admin_subject_path %>
</div>
<table class="table table-striped table-hover">
  <tr>
    <th><%= t ".subject_name" %></th>
    <th><%= t ".description" %></th>
    <th><%= t ".picture" %></th>
    <th><%= t ".time_start" %></th>
    <th><%= t ".time_end" %></th>
    <th><%= t ".status" %></th>
    <th><%= t ".edit" %></th>
    <th><%= t ".delete" %></th>
  </tr>
  <%= render partial: "admin/subjects/subject", collection: @subjects %>
</table>
<%= will_paginate %>

app/views/admin/subjects/new.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".create") %>
<h1><%= t ".create" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>