config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    resources :courses, except: :destroy
    resources :subjects
  end

  resources :users, except: :destroy
  resources :courses
  resources :course_management_users, only: :create
  resources :tasks
  resources :subjects
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
  before_action :correct_permission_admin
  before_action :load_course, only: [:show, :edit, :update]

  def index
    @courses = Course.sort_by_created_at.paginate per_page: Settings.per_page,
      page: params[:page]
  end

  def show; end

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.build course_params
    if @course.save
      flash[:success] = t ".controller.admin.courses.create.success"
      redirect_to admin_courses_path
    else
      flash[:danger] = t ".controller.admin.courses.create.failed"
      render :new
    end
  end

  def edit; end

  def update
    if @course.update_attributes(course_params)
      flash[:success] = t "controller.admin.courses.update.success"
      redirect_to admin_courses_path(@course)
    else
      flash[:danger] = t "controller.admin.courses.update.failed"
      render :edit
    end
  end

  private

  def course_params
    params.require(:course).permit :thumbnail, :name, :description, :time_start,
      :time_end, :status, :creator_id
  end

  def load_course
    @course = Course.find_by id: params[:id]
    return if @course
    flash[:danger] = t "controller.admin.courses.load_course.not_f"
    redirect_to admin_courses_path
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :logged_in_user
  before_action :load_course, only: :show

  def index
    @course_opens = Course.is_open.sort_by_created_at
                          .paginate per_page: Settings.per_page,
                            page: params[:page]
    return if current_user.traine?
    @course_closes = Course.is_close.sort_by_created_at
                           .paginate per_page: Settings.per_page,
                            page: params[:page]
  end

  def show; end

  private

  def load_course
    @course = Course.find_by id: params[:id]
    return if @course
    flash[:danger] = t "controler.courses.not_f"
    redirect_to courses_path
  end
end

app/helpers/admin/courses_helper.rb
module Admin::CoursesHelper
  def get_creator id
    user = User.find_by id: id
    return user.full_name if user
    flash[:danger] = t ".helper.admin.courses.not_f"
    redirect_to :back
  end

  def get_status course
    if course.is_open?
      content_tag(:span, t(".helper.admin.courses.open"),
        class: "btn btn-primary btn-xs")
    else
      content_tag(:span, t(".helper.admin.courses.close"),
        class: "btn btn-danger btn-xs")
    end
  end

  def get_status_select
    Course.statuses
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def check_join_course_management course_id
    current_user.course_managements.find_by(course_id: course_id)
  end

  def load_course_management course
    CourseManagement.load_course_managements(course.id)
  end

  def load_user_is_traine course_id
    user_ids = CourseManagement
               .load_course_managements(course_id)
               .activited
               .pluck(:user_id)
    return User.traine.pluck(:full_name, :id) if user_ids.blank?
    User.load_user_not(user_ids).traine
        .pluck(:full_name, :id)
  end

  def load_course_management_has_course_is_activited course
    course.course_managements.activited
  end
end

app/views/courses/_course_close.html.erb
<% @course_closes.each do |course_close| -%>
  <div class="col-md-4">
    <div class="box box-widget widget-user-2 min-height-300">
      <div class="widget-user-header bg-yellow min-height-150">
        <div class="widget-user-image">
          <%= image_tag(course_close.thumbnail.url, size: Settings.thumbnail_size, alt: course_close.name) if course_close.thumbnail? %>
        </div>
        <h3 class="widget-user-username"><%= course_close.name %></h3>
        <h5 class="widget-user-desc"><%= course_close.user.full_name %></h5>
      </div>
      <div class="box-footer no-padding">
        <ul class="nav nav-stacked">
          <li>
            <span><button class="btn btn-success"><%= t(".subject") %></button> </span>
            <span class="pull-right badge bg-blue"><%= course_close.subjects.size %></span>
          </li>
          <li>
            <%= link_to t(".view_detail"), course_management_path(course_close), class: "btn bg-teal color-palette" %>
          </li>
          <li>
            <%= link_to t(".join_course"), course_management_path(course_close), method: :post, class: "btn bg-teal color-palette", data: { confirm: t(".confirm") } %>
          </li>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/courses/_course_open.html.erb
<% @course_opens.each do |course_open| -%>
  <div class="col-md-4">
    <div class="box box-widget widget-user-2 min-height-300">
      <div class="widget-user-header bg-yellow min-height-150">
        <div class="widget-user-image">
          <%= image_tag(course_open.thumbnail.url, size: Settings.thumbnail_size, alt: course_open.name) if course_open.thumbnail? %>
        </div>
        <h3 class="widget-user-username"><%= course_open.name %></h3>
        <h5 class="widget-user-desc"><%= course_open.user.full_name %></h5>
      </div>
      <div class="box-footer no-padding">
        <ul class="nav nav-stacked">
          <li>
            <span><button class="btn btn-success"><%= t(".subject") %></button> </span>
            <span class="pull-right badge bg-blue"><%= course_open.subjects.size %></span>
          </li>
          <li>
            <%= link_to t(".view_detail"), course_path(course_open), class: "btn bg-teal color-palette" %>
          </li>
          <li>
            <% if check_join_course_management course_open.id %>
              <% if check_join_course_management(course_open.id).activited? %>
                <h4 class="bg-maroon"><%= t(".course_activited") %> </h4>
              <% end %>
              <span class=""> <%= t(".joined_ad") %> <%= l(check_join_course_management(course_open.id).time_join, format: :short) %></span>
              <span class="btn bg-red"><%= link_to t(".leave"), course_management_path(check_join_course_management(course_open.id)), method: :delete %></span>
            <% elsif  %>
              <%= form_for course_open.course_managements.build do |f| %>
                <%= f.hidden_field :course_id, value: course_open.id %>
                <%= f.submit t(".join_course"), class: "btn bg-navy color-palette"%>
              <% end %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/courses/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="row">
      <h2><%= t(".all_course") %></h2>
      <ul class="nav nav-tabs">
        <li class="active">
          <%= link_to t(".course_open"), "#home", "data-toggle": "tab" %>
        </li>
        <% if current_user.trainer? %>
          <li>
            <%= link_to t(".course_close"), "#menu1", "data-toggle": "tab" %>
          </li>
        <% end %>
      </ul>
      <div class="tab-content">
        <div id="home" class="tab-pane fade in active">
          <%= render partial: "course_open", locals: {course_opens: @course_opens} %>
          <p><%= will_paginate @course_opens %></p>
        </div>
        <div id="menu1" class="tab-pane fade">
          <% if current_user.trainer? %>
            <%= render partial: "course_close", locals: {course_closes: @course_closes} %>
            <p><%= will_paginate @course_closes %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/courses/show.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <section class="content">
      <div class="row">
        <div class="col-md-9">
          <div class="box box-widget widget-user-2 min-height-300">
              <div class="widget-user-header bg-yellow min-height-150">
                <div class="widget-user-image">
                  <%= image_tag(@course.thumbnail.url, size: Settings.thumbnail_size, alt: @course.name) if @course.thumbnail? %>
                </div>
                <h3 class="widget-user-username"><%= @course.name %></h3>
                <h5 class="widget-user-desc"><%= @course.user.full_name %></h5>
              </div>
              <div class="box-footer no-padding">
                <ul class="nav nav-stacked">
                  <li>
                    <span><h3><%= t(".subject") %></h3></span>
                    <span class="pull-right badge bg-blue"><%= @course.subjects.size %></span>
                  </li>
                </ul>
                <ul class="nav nav-stacked">
                  <% @course.subjects.each do |subject| %>
                    <div class="row">
                      <div class="col-md-5">
                        <div class="box box-widget widget-user-2 bg-light-blue" >
                            <div class="widget-user-header bg-light-blue">
                              <div class="widget-user-image">
                                <%= image_tag(subject.thumbnail.url, size: Settings.thumbnail_size, alt: subject.name) if subject.thumbnail? %>
                              </div>
                              <h3 class="widget-user-username"><%= subject.name %></h3>
                              <h5 class="widget-user-desc"><%= subject.full_name %></h5>
                            </div>
                          </div>
                      </div>
                    <% end %>
                  </ul>
                </div>
              </div>
          </div>
          <div class="col-md-3">
            <div class="box box-primary">
              <ul><h3><%= t(".trainer") %></h3></ul>
              <% load_course_management(@course).each do |course_management| %>
                <ul class="list-group">
                  <% if course_management.user.trainer? %>
                    <li class="list-group-item"> <%=course_management.user.full_name %> </li>
                  <% end %>
                </ul>
              <% end %>
              <ul><h3><%= t(".traine") %></h3></ul>
              <% load_user_has_course_is_activited(@course).each do |course_management| %>
                <ul class="list-group">
                  <% if course_management.user.traine?%>
                    <li class="list-group-item"> <%=course_management.user.full_name %> </li>
                  <% end %>
                </ul>
              <% end %>
            </div>
            <div class="box box-primary" style="padding: 10px">
              <% if current_user.trainer? %>
                <%= form_for @course.course_managements.build, url: add_user_path, method: :post, class: "form-group" do |f| %>
                  <%= f.select :user_id , load_user_is_traine(@course.id), class: "form-control" %>
                  <%= f.hidden_field :course_id, value: @course.id %>
                  <%= f.hidden_field :status, value: :activited %>
                  <%= f.submit t(".add_traine"), class: "btn btn-primary"%>
                <% end %>
              </ul>
            <% end %>
            <ul><h3><%= t(".traine") %></h3></ul>
            <% load_course_management_has_course_is_activited(@course).each do |course_management| %>
              <ul class="list-group">
                <% if course_management.user.traine?%>
                  <li class="list-group-item"> <%=course_management.full_name %> </li>
                <% end %>
              </ul>
            <% end %>
          </div>
          <div class="box box-primary padding-10">
            <% if current_user.trainer? %>
              <%= form_for @course.course_managements.build, url: course_management_users_path, method: :post, class: "form-group" do |f| %>
                <%= f.select :user_id , load_user_is_traine(@course.id), class: "form-control" %>
                <%= f.hidden_field :course_id, value: @course.id %>
                <%= f.hidden_field :status, value: :activited %>
                <%= f.submit t(".add_traine"), class: "btn btn-primary"%>
              <% end %>
            <% end %>
          </div>
        </div>
    </section>
  </div>