config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    resources :courses, except: :destroy
    resources :subjects
  end

  resources :users, except: :destroy
  resources :courses
  resources :course_management_users, only: :create
  resources :tasks
  resources :subjects
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
  before_action :correct_permission_admin
  before_action :load_course, only: [:show, :edit, :update]

  def index
    @courses = Course.sort_by_created_at.paginate per_page: Settings.per_page,
      page: params[:page]
  end

  def show; end

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.build course_params
    if @course.save
      flash[:success] = t ".controller.admin.courses.create.success"
      redirect_to admin_courses_path
    else
      flash[:danger] = t ".controller.admin.courses.create.failed"
      render :new
    end
  end

  def edit; end

  def update
    if @course.update_attributes(course_params)
      flash[:success] = t "controller.admin.courses.update.success"
      redirect_to admin_courses_path(@course)
    else
      flash[:danger] = t "controller.admin.courses.update.failed"
      render :edit
    end
  end

  private

  def course_params
    params.require(:course).permit :thumbnail, :name, :description, :time_start,
      :time_end, :status, :creator_id
  end

  def load_course
    @course = Course.find_by id: params[:id]
    return if @course
    flash[:danger] = t "controller.admin.courses.load_course.not_f"
    redirect_to admin_courses_path
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :logged_in_user
  before_action :load_course, only: :show

  def index
    @course_opens = Course.is_open.sort_by_created_at
                          .paginate per_page: Settings.per_page,
                            page: params[:page]
    return if current_user.traine?
    @course_closes = Course.is_close.sort_by_created_at
                           .paginate per_page: Settings.per_page,
                            page: params[:page]
  end

  def show; end

  private

  def load_course
    @course = Course.find_by id: params[:id]
    return if @course
    flash[:danger] = t "controler.courses.not_f"
    redirect_to courses_path
  end
end

app/helpers/admin/courses_helper.rb
module Admin::CoursesHelper
  def get_creator id
    user = User.find_by id: id
    return user.full_name if user
    flash[:danger] = t ".helper.admin.courses.not_f"
    redirect_to :back
  end

  def get_status course
    if course.is_open?
      content_tag(:span, t(".helper.admin.courses.open"),
        class: "btn btn-primary btn-xs")
    else
      content_tag(:span, t(".helper.admin.courses.close"),
        class: "btn btn-danger btn-xs")
    end
  end

  def get_status_select
    Course.statuses
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def check_join_course_management course_id
    current_user.course_managements.find_by(course_id: course_id)
  end

  def load_course_management course
    CourseManagement.load_course_managements(course.id)
  end

  def load_user_is_traine course_id
    user_ids = CourseManagement
               .load_course_managements(course_id)
               .activited
               .pluck(:user_id)
    return User.traine.pluck(:full_name, :id) if user_ids.blank?
    User.load_user_not(user_ids).traine
        .pluck(:full_name, :id)
  end

  def load_course_management_has_course_is_activited course
    course.course_managements.activited
  end
end

app/views/admin/courses/_course.html.erb
<tr>
  <td>
    <%= image_tag(course.thumbnail.url, size: Settings.thumbnail_size, alt: course.name) if course.thumbnail?  %>
  </td>
  <td>
    <%= link_to course.name, admin_course_path(course) %>
  </td>
  <td><%= l(course.time_start, format: :short) %></td>
  <td><%= l(course.time_end, format: :short) %></td>
  <td><%= l(course.created_at, format: :short) %></td>
  <td><%= get_status course %></td>
  <td><%= get_creator course.creator_id %></td>
</tr>

app/views/admin/courses/_form.html.erb
<%= form_for [:admin, @course] do |f| %>
  <div class="row">
    <div class="col-md-5">
      <%= f.label t(".thumbnail") %>:
      <%= f.file_field :thumbnail, accept: Settings.accept_picture, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10">
      <%= f.label t(".name") %>:
      <%= f.text_field :name , class: "form-control" %>
    </div>
  </div>
  <div class="row section">
    <div class="col-md-10">
      <%= f.label t(".description") %>:
      <%= f.text_area :description, size: Settings.description_size, class: "form-control" %>
    </div>
  </div>
  <div class="row section">
    <div class="col-md-3">
      <%= f.label t ".time_start" %>:
      <%= f.date_field :time_start, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label t(".time_end") %>:
      <%= f.date_field :time_end, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <%= f.label t(".status") %>:
      <%= f.select :status, get_status_select.keys.to_a.map { |v| [v] }, selected: :is_open,  include_blank: true, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/courses/edit.html.erb
<% provide(:button_text, t(".save")) %>
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <h2 class="bg-primary"><%= t(".title") %> </h2>
        <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/courses/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-2">
      <%= link_to  t(".creat"), new_admin_course_path, class: "btn btn-block btn-success btn-lg" %>
    </div>
    <div class="col-md-12">
      <h2 class="bg-primary"><%= t(".title") %> </h2>
      <table class="table">
        <tr>
          <th></th>
          <th><%= t(".name") %></th>
          <th><%= t(".time_start") %></th>
          <th><%= t(".time_end") %></th>
          <th><%= t(".created_at") %></th>
          <th><%= t(".status") %></th>
          <th><%= t(".creator") %></th>
        </tr>
        <tr>
          <%= render @courses %>
        </tr>
      </table>
      <%= will_paginate @courses %>
    </div>
  </div>
</div>

app/views/admin/courses/new.html.erb
<% provide(:button_text, t(".create")) %>
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <h2 class="bg-primary"><%= t(".create_title") %> </h2>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/courses/show.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-2">
      <%= link_to  t(".edit_course"), edit_admin_course_path(@course), class: "btn btn-block btn-success btn-lg" %>
    </div>
    <div class="container-fuild">
      <h2 class="bg-primary"><%= @course.name %> </h2>
      <div class="row">
        <div class="col-md-5">
          <%= image_tag(@course.thumbnail.url, size: Settings.thumbnail_size, alt: @course.name) if @course.thumbnail? %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5">
          <%= label_tag t(".name") %>:
          <%= @course.name %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-10">
          <%= label_tag t(".description") %>:
          <%= @course.description %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <%= label_tag t(".time_start") %>:
          <%= l(@course.time_start, format: :short) %>
        </div>
        <div class="col-md-3">
          <%= label_tag t(".time_end") %>:
          <%= l(@course.time_end, format: :short) %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <%= label_tag t(".created_at") %>:
          <%= l(@course.created_at, format: :short) %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <%= label_tag t(".status") %>:
          <%= get_status @course %>
        </div>
        <div class="col-md-5">
          <%= label_tag t(".creator") %>:
          <%= get_creator @course.creator_id %>
        </div>
      </div>
    </div>
    <div class="col-md-12">
    </div>
  </div>
</div>