config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    resources :courses, except: :destroy
    resources :subjects
  end

  resources :users, except: :destroy
  resources :courses
  resources :course_management_users, only: :create
  resources :tasks
  resources :subjects
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".text" %>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
  <%= link_to(root_path, class: "logo") do %>
    <span class="logo-mini"><b>S</b>UN</span>
    <span class="logo-lg"><b>SUN</b> * </span>
  <% end %>
  <nav class="navbar navbar-static-top">
    <%= link_to("#", class: "sidebar-toggle", "data-toggle": "push-menu", role: "button") do %>
      <span class="sr-only"></span>
    <% end %>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li class="dropdown">
            <%= link_to("#", class: "dropdown-toggle", "data-toggle": "dropdown") do %>
              <%= current_user.email %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), users_path %></li>
              <li><%= link_to t(".setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
          <% else %>
            <li><%= link_to t(".login"), login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_header_admin.html.erb
<header class="main-header">
  <%= link_to(users_path, class: "logo") do %>
    <span class="logo-mini"><b>S</b>UN</span>
    <span class="logo-lg"><b>SUN</b> * </span>
  <% end %>
  <nav class="navbar navbar-static-top">
    <%= link_to("#", class: "sidebar-toggle", "data-toggle": "push-menu", role: "button") do %>
      <span class="sr-only"></span>
    <% end %>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li class="dropdown">
            <%= link_to("#", class: "dropdown-toggle", "data-toggle": "dropdown") do %>
              <%= current_user.email %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), users_path %></li>
              <li><%= link_to t(".setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
          <% else %>
            <li><%= link_to t(".login"), login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_left_content.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <div class="user-panel">
    </div>
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header"><%= t(".main_navigation") %></li>
      <!-- managements course-->
      <li class="active treeview">
        <%= link_to("#", class: "fa fa-dashboard") do %>
          <%= t(".management_course") %>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        <% end %>
        <ul class="treeview-menu">
          <li class="active">
            <%= link_to("#") do %>
              <i class="fa fa-circle-o"></i>
              <%= t(".lits_course")%>
            <% end %>
          </li>
          <li>
            <%= link_to("#") do %>
              <i class="fa fa-circle-o"></i>
              <%= t(".create_course")%>
            <% end %>
          </li>
        </ul>
      </li>
      <!-- End -->
      <!-- managements subjects-->
      <li class="active treeview">
        <%= link_to("#", class: "fa fa-dashboard") do %>
          <%= t(".management_subject") %>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        <% end %>
        <ul class="treeview-menu">
          <li class="active">
            <%= link_to("#") do %>
              <i class="fa fa-circle-o"></i>
              <%= t(".lits_subject")%>
            <% end %>
          </li>
          <li>
            <%= link_to("#") do %>
              <i class="fa fa-circle-o"></i>
              <%= t(".create_subject")%>
            <% end %>
          </li>
        </ul>
      </li>
      <!-- end -->
      <!-- managements task-->
      <li class="active treeview">
        <%= link_to("#", class: "fa fa-dashboard") do %>
          <%= t(".management_task") %>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        <% end %>
        <ul class="treeview-menu">
          <li class="active">
            <%= link_to("#") do %>
              <i class="fa fa-circle-o"></i>
              <%= t(".lits_task")%>
            <% end %>
          </li>
          <li>
            <%= link_to("#") do %>
              <i class="fa fa-circle-o"></i>
              <%= t(".create_task")%>
            <% end %>
          </li>
        </ul>
      </li>
      <!-- end -->
    </ul>
  </section>
</aside>

app/views/layouts/_left_content_admin.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <div class="user-panel">
    </div>
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header"><%= t(".main_navigation") %></li>
      <!-- managements course-->
      <li class="active treeview">
        <%= link_to("#", class: "fa fa-dashboard") do %>
          <%= t(".management_course") %>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        <% end %>
        <ul class="treeview-menu">
          <li class="active">
            <%= link_to("#") do %>
              <i class="fa fa-circle-o"></i>
              <%= t(".lits_course")%>
            <% end %>
          </li>
          <li>
            <%= link_to("#") do %>
              <i class="fa fa-circle-o"></i>
              <%= t(".create_course")%>
            <% end %>
          </li>
        </ul>
      </li>
      <!-- End -->
      <!-- managements subjects-->
      <li class="active treeview">
        <%= link_to("#", class: "fa fa-dashboard") do %>
          <%= t(".management_subject") %>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        <% end %>
        <ul class="treeview-menu">
          <li class="active">
            <%= link_to("#") do %>
              <i class="fa fa-circle-o"></i>
              <%= t(".lits_subject")%>
            <% end %>
          </li>
          <li>
            <%= link_to("#") do %>
              <i class="fa fa-circle-o"></i>
              <%= t(".create_subject")%>
            <% end %>
          </li>
        </ul>
      </li>
      <!-- end -->
      <!-- managements task-->
      <li class="active treeview">
        <%= link_to("#", class: "fa fa-dashboard") do %>
          <%= t(".management_task") %>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        <% end %>
        <ul class="treeview-menu">
          <li class="active">
            <%= link_to("#") do %>
              <i class="fa fa-circle-o"></i>
              <%= t(".lits_task")%>
            <% end %>
          </li>
          <li>
            <%= link_to("#") do %>
              <i class="fa fa-circle-o"></i>
              <%= t(".create_task")%>
            <% end %>
          </li>
        </ul>
      </li>
      <!-- end -->
    </ul>
  </section>
</aside>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= render "layouts/rails_default" %>
  <%= render "layouts/shim" %>
</head>
<body class="hold-transition skin-blue sidebar-mini padding0">
  <div class="wrapper">
    <%= render "layouts/header_admin" %>
    <%= render "layouts/left_content_admin" %>
    <div class="content-wrapper">
      <section class="content">
        <%= yield %>
      </section>
    </div>
    <div class="control-sidebar-bg"></div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= render "layouts/rails_default" %>
  <%= render "layouts/shim" %>
</head>
<body class="hold-transition skin-blue sidebar-mini padding0">
  <div class="wrapper">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= render "layouts/header" %>
    <% if logged_in? %>
      <%= render "layouts/left_content" %>
    <% end %>
    <div class="content-wrapper" >
      <section class="content padding-t">
        <%= yield %>
      </section>
    </div>
    <div class="control-sidebar-bg"></div>
  </div>
</body>
</html>